const fs = require('fs')
console.log("Hello")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")
console.log("Bye")